development:
  adapter: postgresql
  encoding: unicode
  database: mockup_development
  pool: 5
  username: mockup
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mockup_test
  pool: 5
  username: mockup
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mockup_production
  pool: 5
  username: mockup
  password: